spring.application.name=account-service

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/account_db}
spring.datasource.username=${DB_USERNAME:account_user}
spring.datasource.password=${DB_PASSWORD:account_password}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info